apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: create-todo-job
spec:
  # Every hour
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: create-todo-job
            image: todo-job:v1
            imagePullPolicy: IfNotPresent
            env:
              - name: BACKEND_URL
                value: "http://todo-backend-svc:2351"
