apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/todos/namespace.yaml
  - manifests/storage-class.yaml
  - manifests/todos/db/db.yaml

  - manifests/todos/volumes/todo-app-pv.yaml
  - manifests/todos/volumes/todo-app-pvc.yaml

  - manifests/todos/todo-backend/deployment.yaml
  - manifests/todos/todo-backend/cluster.yaml
  - manifests/todos/todo-backend/cronjob.yaml

  - manifests/todos/todo-app/configmap.yaml
  - manifests/todos/todo-app/deployment.yaml
  - manifests/todos/todo-app/cluster.yaml

  - manifests/todos/ingress.yaml

images:
  - name: PROJECT/TODO_APP_IMAGE
    newName: todo-app
    newTag: v12
  - name: PROJECT/TODO_BACKEND_IMAGE
    newName: todo-backend
    newTag: v4
