apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: pixabay-apikey
data:
    #ENC[AES256_GCM,data:j3tfBG5nKeSwLceT9AW2pk29/E6Y,iv:8IF433SG/cgFCq7Hcm8LgqcwZRkuqOQHl2+Jtn/9X6I=,tag:aA0+4IQdnyPPLEgVmS7dGA==,type:comment]
    SECRET_IN_ENV: ENC[AES256_GCM,data:/GgxAzL/VfUxv7tRRDLLIj7tvr2G7FAuIJuIXqKUBlmeZgerco68kZi1aBHJJp+wzay9lvNuEHw=,iv:G40nLzVOgTJtsKkG9C4ZO8I9WlSverWaMiUYAzRuDaY=,tag:LMKAeuuYoO3F19HxzohNjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSlRKblJKai9jMUlEamFE
            b1h3Mk9KZXhwbThJMWMxSG8rQTR0eGdyZ0hvCjJNVmt1WnVFZGtGS2dLQ0dpQ1Y1
            clE2RE53dWt5bUNPVjVXQm1EUnRQY00KLS0tIFBrOVdoczRuSnZJM3RNcmt0UW5a
            NkVYa3djajBHVTBGYUlVYmZpNEV2M0EKvVWz0GX+jd2eH5N3WPi39FiZWcEFII+F
            ondrzd9D7B5q1Bp96NYjZwYqaDWORYUuH1qnff3IN8m4LchJsc8nWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16fc6a308hwul3dkkugmxf4vdvmgxul3p5fv375sdsuga0ulhc42s4d40xu
    encrypted_regex: ^(data)$
    lastmodified: "2026-06-16T22:32:46Z"
    mac: ENC[AES256_GCM,data:DepAviGlpaxo8Vlz0zFIYYJfe5bfWJpOGXVht+J23u9D7xCca6TdjKuELGsRhE3Rq4t3QhyWBDFihGp8la6o6Zyfzn124qqMfxJpBJZg4z0Tun0Ezc3Dqx2YbRtt0rQ96pQSpREQIg0TfSenhgXtzs/+csknwpdkzY2FkTHBKg0=,iv:1VwnElqTAZWVPuE7Gn3voIJCEDSM2n8rlDgTbxdw/fA=,tag:fpWwTnVyvzBDl0CMpWkwqw==,type:str]
    version: 3.13.1
