apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: log-output-api
          imagePullPolicy: IfNotPresent
          image: log-output:v3
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
          env:
            - name: IS_API
              value: "true"
            - name: PORT
              value: "3000"
        - name: log-output-console
          imagePullPolicy: IfNotPresent
          image: log-output:v3
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
          env:
            - name: IS_API
              value: "false"
