apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: shared-log
          emptyDir: {}
        # - name: persist-log-ping-pv
        #   persistentVolumeClaim:
        #     claimName: persist-log-ping-pvc
      containers:
        - name: log-output-api
          imagePullPolicy: IfNotPresent
          image: log-output:v5
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
            # - name: persist-log-ping-pv
            #   mountPath: /usr/src/app/pings
          env:
            - name: IS_API
              value: "true"
            - name: PORT
              value: "3000"
        - name: log-output-console
          imagePullPolicy: IfNotPresent
          image: log-output:v5
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
            # - name: persist-log-ping-pv
            #   mountPath: /usr/src/app/pings
          env:
            - name: IS_API
              value: "false"
