apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persist-log-ping-pvc
spec:
  storageClassName: my-example-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
