apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: persist-todo-app-pv
          persistentVolumeClaim:
            claimName: persist-todo-app-pvc
      containers:
        - name: todo-app
          imagePullPolicy: IfNotPresent
          image: todo-app:v11
          volumeMounts:
            - name: persist-todo-app-pv
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: MY_IMAGE_URL # key inside the configmap
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
