apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: persist-todo-app-pvc
spec:
  volumeName: persist-todo-app-pv
  storageClassName: my-example-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
