apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: shared-log
          emptyDir: {}
        # - name: persist-log-ping-pv
        #   persistentVolumeClaim:
        #     claimName: persist-log-ping-pvc
        - name: log-configmap
          configMap:
            name: log-configmap
      containers:
        - name: log-output-api
          imagePullPolicy: IfNotPresent
          image: log-output:v6
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
            # - name: persist-log-ping-pv
            #   mountPath: /usr/src/app/pings
          env:
            - name: IS_API
              value: "true"
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
        - name: log-output-console
          imagePullPolicy: IfNotPresent
          image: log-output:v6
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/logs
            # - name: persist-log-ping-pv
            #   mountPath: /usr/src/app/pings
            - name: log-configmap
              mountPath: /etc/config
          env:
            - name: IS_API
              value: "false"
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: pixabay-apikey
                  key: SECRET_IN_ENV # key inside the secret
          envFrom:
            - secretRef:
                name: todo-apikey # API
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
