apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: persist-log-ping-pv
          persistentVolumeClaim:
            claimName: persist-log-ping-pvc
      containers:
        - name: ping
          imagePullPolicy: IfNotPresent
          image: ping:v3
          volumeMounts:
            - name: persist-log-ping-pv
              mountPath: /usr/src/app/pings
